// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: owurwkcewzagbfehrhrd

class SupabaseConfig {
  static const String supabaseUrl = 'https://owurwkcewzagbfehrhrd.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dXJ3a2Nld3phZ2JmZWhyaHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNTUzMzAsImV4cCI6MjA4MDkzMTMzMH0.un-pSRrkwULzgFG4Jjym2ePWHqRYQVLC2-b-P0EHLn0';
}
